### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by Exlsunshine**
Fix calling convert_sklearn

### CODE REVIEW

**Comment by sdpython** [comment]
Which version of sklearn-onnx are you using? The version from master branch shoud be working. The version on pypi is too old but should be updated soon.

**Comment by sdpython** [comment]
I think the best would be to try catch the first call with dtype and then to fallback to the second call without if it fails.

**Comment by Exlsunshine** [comment]
> Which version of sklearn-onnx are you using? The version from master branch shoud be working. The version on pypi is too old but should be updated soon.

0.21.0

**Comment by Exlsunshine** [comment]
> I think the best would be to try catch the first call with dtype and then to fallback to the second call without if it fails.

Yes, adding a ```try catch``` is better, maybe I was using an old version of skl-onnx and then I encountered the error.

**Pull request merged**
